# Schedule


##  Lecture 1 Introduction 30-01 (MM/CF)

### In class:

organization of the course
rules of the game
basics Markdown
basics python
basics R
To prepare before class:

Install Anaconda, R and R studio and bring your laptop


## Lecture 2 Competition law and its objectives 01-02 (MM)
In class:

classroom experiment competition
presentation about the role of competition and regulation

### To prepare before class:

Motta, Chapter 1.
European Commission (2014). The European Union explained: Competition. Making markets work better. (http://ec.europa.eu/competition/publications/)
3.3 Lecture 3 Market definition and the measurement of competition and market power 06-02 (MA/RC)
In class:

## Estimation of market power

### In class

guest lecture by Ramsis Croes (NZa/Erasmus Univeristy)
demonstration of a logit demand estimation

### To prepare before class:

Motta, Chapters 2 and 3.
Gaynor: Paper will be uploaded to students


## Lecture 4 Collusion and Horizontal Agreements 08-02 (MM)

### In class:

classroom experiment with strategic interaction duopolies
presentation about collusion

### To prepare:

Motta, Chapter 4 (with the exception of 4.3)

##  Lecture 5 Continuation of Lecture 2, deterrence and cartels 13-02 (CF)

### In class:

theory

### To prepare before class:

Motta, Chapter 4 (with the exception of 4.3)



## Lecture 6 Article 102 TFEU: Abuse of a dominant position 14-02 (MA/AB)

In class: 

- lecture 

To prepare before class:

- Motta, chapter 7
- European Commission: Guidance on enforcement priorities in applying Article 102 of the EC Treaty to abusive exclusionary conduct by dominant undertakings, 2009

## Lecture 7 Mergers 19-02 (MA)

In class:

- lecture
- guest lecture from ACM about merger assessment

To prepare before class : 

- Motta, Chapter 5 (with the exception of 5.4) and chapter 6 (6.2.4, 6.4.2, 6.6) (EB)
- European Commission: Guidelines on the assessment of horizontal mergers, 2004
- European Commission: Guidelines on the assessment of non-horizontal mergers, 2008

## Lecture 8 Leniency schemes and bid rigging  21-02 (CF)

In class

- Lecture

Prepare before class:

 - https://www.researchgate.net/publication/300700468_Exploitation_and_Induced_Tacit_Collusion_A_Classroom_Experiment_of_Corporate_Leniency_Programs
- Bigoni, M., Fridolfson, S., Le Coq, C. and G. Spagnolo (2012). Fines, leniency and rewards in antitrust. The Rand Journal of Economics 43 (2), 368-390.
- McAfee, R. P., & McMillan, J. (1992). Auctions and Bidding Rings. American Economic Review, 82(3), 579-599.


## Lecture 9 Horizontal mergers - part 2 04-03 (MA)

In class:

- Lecture

To prepare before class:

- Farrell, J., & Shapiro, C. (1990). Horizontal mergers: an equilibrium analysis. The American Economic Review, 80 (1), 107-126
- Federico, G., Langus, G. and T. Valletti (2017). Horizontal mergers and product innovation: an economic framework. UPF Working paper 2017-1579. [Available at](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2999178M) 
- Ivaldi & F. Verboven (2005): Quantifying the effects from horizontal mergers in European competition policy [to download](https://ideas.repec.org/p/cpr/ceprdp/2697.html)



## Lecture 10 Price regulation 06-03 (MM/BP)

In class

- Presentation about the theory of regulation
- Presentation from Bas Postema (ACM) about the regulation of the Dutch electricity networks

To prepare

- P. Agrell and P. Bogetoft (2004) Evolutionary Regulation: From CPI-X towards Contestability
[download](https://www.sumicsid.com/reg/papers/encore.pdf)

- ACM (2017) Incentive regulation of the gas and electricity networks in the Netherlands [download](https://www.acm.nl/sites/default/files/old_publication/publicaties/17231_incentive-regulation-of-the-gas-and-elektricity-networks-in-the-netherlands-2017-05-17.pdf)


## Lecture 11 Benchmarking 11-03 (MM/VS)

In class

- Presentation from Victoria Shestalova (NZa) about DEA
- DEA in R


To prepare:

- P. Agrell and P. Bogetoft (2002), DEA-Based incentive regimes in health care provision [to download](https://www.researchgate.net/profile/Peter_Bogetoft/publication/23515165_DEA-Based_Incentive_Regimes_in_Health-Care_Provision/links/0912f50ae2f961fe8b000000.pdf)
- A. Arcos-Vargas, F. Núñez-Hernández, Gabriel Villa-Caro, (2017), A DEA analysis of electricity distribution in Spain: An industrial policy recommendation, Energy Policy 102 (583 - 592)




## Lecture 12 Vertical integration 13-03 (MM/KK)

In class:

- classroom experiment vertical mergers
- presentation about vertical mergers and vertical restraints by Katalin Katona (NZa/Tilburg University)

To prepare before class:

- Motta, Chapter 6 (with the exception of the two starred (**) sections)


## Lecture 13 Abuse of a dominant position: predatory pricing 18-03 (MA/MM)

In class:

- classroom experiment
- lecture

To prepare before class:

- Goolsbee, A., Syverson, C. (2008). How do incumbents respond to the threat of entry? Evidence from the major airline. The Quartely Journal of Economics, Vol. 123, Issue 4, 1611-1633 https://academic.oup.com/qje/article/123/4/1611/1933206
- Nurski, L., Verboven. F. (2016). Exclusive Dealing as a Barrier to Entry? Evidence from Automobiles. The review of economic studies, Vol 83, Issue 3, 1156-1188., https://academic.oup.com/restud/article/83/3/1156/2461273


## Problems

The idea with these lectures is that students in teams will present solutions to policy makers for some competition and regulation problems. The students will present the case in class to the government. 

the presentation (20 mins) should:

- describe the problem
- discuss the relevant academic literature
- present policy options (including pro's and cons from an economic perspective)


## Lecture 14 Transparancy of prices in the hospital market 20-03 (MM)

- Teams A, B, C, D
 
 
 
## Lecture 15 Competition problem number 2 25-03 (MA)

- teams E, F, G, H

## Lecture 16 Regulation problem 27-03 (MM)



- teams I, J, K, L


## Cases

In the cases students will form new teams. Some teams will represent the government (Comptetition Authority or Regulator), the other teams will represent the firms. We will provide some data, so the teams can also do a quantative analysis.

The students not assigned to a team will form the jury and will have to formulate a verdict.

## Lecture 17 Competition case 01-04 (MA) 

a.  Competition Authority: teams 1 and 2
b.  Firms: teams 3 and 4

## Lecture 18 Regulation case 03-04 (MM)

Note: Nursing homes

a.  Regulator: teams 5 and 6
b.  Firms: teams 7 and 8
=======
Finally, we urge you to use google (or other search engines like DuckDuckGo) and stackoverflow with your assignments. Some students find this weird at the beginning: should we not teach you everything that you need to know? The answer is no for a number of reasons. First, even professional programmers use google and stackoverflow all the time. If you are on Quora; see this post and this one. Second, python and R are open source and lots of people work with it. If you encounter a problem, chances are that someone else had the same problem and knows the solution to it. There is not need to "invent the wheel". Use the resources available to you. If you copy a lot of code, you should add a reference. Finally, because python and R are open source, they develop rapidly. The things that we teach you now, will be obsolete in a couple of years time. Hence, you need to be able to find your way around also in 10 years time. To start practicing this, use google now.
>>>>>>> 54edd162eaf857e745bc2b1bfdd68064d89af608

The only warning here is: at the exam you will not have access to the whole internet. So, also make sure that you can find help in the jupyter notebook. We will practice this in class.
